In [1]:
# Define hyper-parameters and other size
N=30 # number of samples
K=3  # the number of classes
D=4  # size of dimension OR number of independent variables
H=10 # size of hidden layer


In [2]:
import sys
import numpy as np
np.random.seed(42)
# X is input samples
X=np.round(np.random.rand(N,D),2)
# R is the output
R=np.repeat([[1,0,0], [0,1,0], [0,0,1]],10, axis=0)

In [3]:
np.c_[X,R]

array([[0.37, 0.95, 0.73, 0.6 , 1.  , 0.  , 0.  ],
       [0.16, 0.16, 0.06, 0.87, 1.  , 0.  , 0.  ],
       [0.6 , 0.71, 0.02, 0.97, 1.  , 0.  , 0.  ],
       [0.83, 0.21, 0.18, 0.18, 1.  , 0.  , 0.  ],
       [0.3 , 0.52, 0.43, 0.29, 1.  , 0.  , 0.  ],
       [0.61, 0.14, 0.29, 0.37, 1.  , 0.  , 0.  ],
       [0.46, 0.79, 0.2 , 0.51, 1.  , 0.  , 0.  ],
       [0.59, 0.05, 0.61, 0.17, 1.  , 0.  , 0.  ],
       [0.07, 0.95, 0.97, 0.81, 1.  , 0.  , 0.  ],
       [0.3 , 0.1 , 0.68, 0.44, 1.  , 0.  , 0.  ],
       [0.12, 0.5 , 0.03, 0.91, 0.  , 1.  , 0.  ],
       [0.26, 0.66, 0.31, 0.52, 0.  , 1.  , 0.  ],
       [0.55, 0.18, 0.97, 0.78, 0.  , 1.  , 0.  ],
       [0.94, 0.89, 0.6 , 0.92, 0.  , 1.  , 0.  ],
       [0.09, 0.2 , 0.05, 0.33, 0.  , 1.  , 0.  ],
       [0.39, 0.27, 0.83, 0.36, 0.  , 1.  , 0.  ],
       [0.28, 0.54, 0.14, 0.8 , 0.  , 1.  , 0.  ],
       [0.07, 0.99, 0.77, 0.2 , 0.  , 1.  , 0.  ],
       [0.01, 0.82, 0.71, 0.73, 0.  , 1.  , 0.  ],
       [0.77, 0.07, 0.36, 0.12,

In [4]:
# Adding some pattern into X
X[:10,:]=X[:10,:]*2
X[10:20,:]=X[10:20,:]*5
X

array([[0.74, 1.9 , 1.46, 1.2 ],
       [0.32, 0.32, 0.12, 1.74],
       [1.2 , 1.42, 0.04, 1.94],
       [1.66, 0.42, 0.36, 0.36],
       [0.6 , 1.04, 0.86, 0.58],
       [1.22, 0.28, 0.58, 0.74],
       [0.92, 1.58, 0.4 , 1.02],
       [1.18, 0.1 , 1.22, 0.34],
       [0.14, 1.9 , 1.94, 1.62],
       [0.6 , 0.2 , 1.36, 0.88],
       [0.6 , 2.5 , 0.15, 4.55],
       [1.3 , 3.3 , 1.55, 2.6 ],
       [2.75, 0.9 , 4.85, 3.9 ],
       [4.7 , 4.45, 3.  , 4.6 ],
       [0.45, 1.  , 0.25, 1.65],
       [1.95, 1.35, 4.15, 1.8 ],
       [1.4 , 2.7 , 0.7 , 4.  ],
       [0.35, 4.95, 3.85, 1.  ],
       [0.05, 4.1 , 3.55, 3.65],
       [3.85, 0.35, 1.8 , 0.6 ],
       [0.86, 0.62, 0.33, 0.06],
       [0.31, 0.33, 0.73, 0.64],
       [0.89, 0.47, 0.12, 0.71],
       [0.76, 0.56, 0.77, 0.49],
       [0.52, 0.43, 0.03, 0.11],
       [0.03, 0.64, 0.31, 0.51],
       [0.91, 0.25, 0.41, 0.76],
       [0.23, 0.08, 0.29, 0.16],
       [0.93, 0.81, 0.63, 0.87],
       [0.8 , 0.19, 0.89, 0.54]])

In [5]:
#Initialize all v ih and w hj to rand(−0.01, 0.01)

v=np.random.uniform(-0.01,0.01,(K,H+1))
w=np.random.uniform(-0.01,0.01,(H,D+1))

In [6]:
np.round(w,3)

array([[-0.   ,  0.01 , -0.005,  0.003,  0.005],
       [-0.005,  0.005, -0.003,  0.003,  0.003],
       [ 0.001, -0.008,  0.007, -0.004, -0.006],
       [-0.009,  0.002,  0.004, -0.01 ,  0.   ],
       [-0.005,  0.003, -0.007,  0.004, -0.002],
       [ 0.009, -0.007, -0.003, -0.008,  0.008],
       [ 0.008, -0.005,  0.003,  0.006,  0.001],
       [ 0.001, -0.005, -0.008,  0.008,  0.008],
       [ 0.003, -0.003, -0.003,  0.005,  0.008],
       [ 0.008,  0.006,  0.003, -0.008, -0.007]])

In [7]:
#Adding Ones to the X as first bias input
X=np.c_[np.ones(30), X]
X

array([[1.  , 0.74, 1.9 , 1.46, 1.2 ],
       [1.  , 0.32, 0.32, 0.12, 1.74],
       [1.  , 1.2 , 1.42, 0.04, 1.94],
       [1.  , 1.66, 0.42, 0.36, 0.36],
       [1.  , 0.6 , 1.04, 0.86, 0.58],
       [1.  , 1.22, 0.28, 0.58, 0.74],
       [1.  , 0.92, 1.58, 0.4 , 1.02],
       [1.  , 1.18, 0.1 , 1.22, 0.34],
       [1.  , 0.14, 1.9 , 1.94, 1.62],
       [1.  , 0.6 , 0.2 , 1.36, 0.88],
       [1.  , 0.6 , 2.5 , 0.15, 4.55],
       [1.  , 1.3 , 3.3 , 1.55, 2.6 ],
       [1.  , 2.75, 0.9 , 4.85, 3.9 ],
       [1.  , 4.7 , 4.45, 3.  , 4.6 ],
       [1.  , 0.45, 1.  , 0.25, 1.65],
       [1.  , 1.95, 1.35, 4.15, 1.8 ],
       [1.  , 1.4 , 2.7 , 0.7 , 4.  ],
       [1.  , 0.35, 4.95, 3.85, 1.  ],
       [1.  , 0.05, 4.1 , 3.55, 3.65],
       [1.  , 3.85, 0.35, 1.8 , 0.6 ],
       [1.  , 0.86, 0.62, 0.33, 0.06],
       [1.  , 0.31, 0.33, 0.73, 0.64],
       [1.  , 0.89, 0.47, 0.12, 0.71],
       [1.  , 0.76, 0.56, 0.77, 0.49],
       [1.  , 0.52, 0.43, 0.03, 0.11],
       [1.  , 0.03, 0.64,

In [8]:
import math


def get_accuracy(x, r, H, K, D, v, w):
    
    error_score = 0
    for t in range(len(x)):
            
        #feed forward of hidden units
        z = []
        z.append(1)

        for h in range(1,H):
            z.append(0)
            for j in range(D):
                z[h] = z[h] + w[h,j]*x[t,j]

        z_bounded = []
        z_bounded.append(1)

        for index in range(1,len(z)):
            if z[index] >=0:
                z_bounded.append(1/(1+math.exp(-z[index] )))
            else:
                z_bounded.append(math.exp(z[index])/(1+math.exp(z[index])))

        o = []
        y = []
        for i in range(K):
            o.append(0)
            for h in range(H):
                o[i] = o[i] + v[i,h]*z_bounded[h]

        #feed forward of outputs units
        max_o = max(o)
        o2 = [math.exp(x-max_o) for x in o]
        denom = sum(o2)

        for i in range(K):
            y.append(o2[i]/denom)

        if r[t].argmax() == y.index(max(y)):
            error_score = error_score + 1.0
    
    return (error_score/len(x))


            
            
            
            
# See Fig 11.11 for the pseudocode
def back_prop(x,r,H,K,D,step_size,accuracy_stop,iterations, Alpha, A, B):

    np.random.seed(42)
    
    v_weights = np.zeros(shape=(K,H))
    w_weights = np.zeros(shape=(H,D))
    w_weights_prev = np.zeros(shape=(H,D))
    alpha = Alpha  #momentume
    a = A  #adaptive
    b = B  #adaptive
        
    delta = sys.float_info.max
    
    for i in range(K):
        for h in range(H):
            v_weights[i,h] = np.random.uniform(-0.01, 0.01)
    
    for h in range(1,H):
        for j in range(D):
            w_weights[h,j] = np.random.uniform(-0.01, 0.01)
        
    error_prev = 0 #0% correct
        
    for run in range(iterations):
        error_score = 0
        
        delta_v = np.zeros(shape=(K,H))
        delta_w = np.zeros(shape=(H,D))
        delta_w_past = np.zeros(shape=(H,D))
        
        
        for t in range(len(x)):
            
            #feed forward of hidden units
            z = []
            z.append(1)
            
            for h in range(1,H):
                z.append(0)
                for j in range(D):
                    z[h] = z[h] + w_weights[h,j]*x[t,j]
            
            z_bounded = []
            z_bounded.append(1)
            
            for index in range(1,len(z)):
                if z[index] >=0:
                    z_bounded.append(1/(1+math.exp(-z[index] )))
                else:
                    z_bounded.append(math.exp(z[index])/(1+math.exp(z[index])))

            o = []
            y = []
            for i in range(K):
                o.append(0)
                for h in range(H):
                    o[i] = o[i] + v_weights[i,h]*z_bounded[h]
            
            #feed forward of outputs units
            max_o = max(o)
            o2 = [math.exp(x-max_o) for x in o]
            denom = sum(o2)
            
            for i in range(K):
                y.append(o2[i]/denom)
                
            if r[t].argmax() == y.index(max(y)):
                error_score = error_score + 1  
        
            for i in range(K):
                for h in range(H):                   
                    delta_v[i,h] = step_size*(r[t,i]-y[i])*z_bounded[h]
            
            for h in range(1,H):
                diff = 0
                for i in range(K):
                    diff = diff + (r[t,i]-y[i])*v_weights[i,h]
                for j in range(D):
                    delta_w[h,j] = step_size*diff*z_bounded[h]*(1-z_bounded[h])*x[t,j] + delta_w_past[h,j]*alpha
                    delta_w_past[h,j] = delta_w[h,j] 
                    
            for i in range(K):
                for h in range(H):
                    v_weights[i,h] = v_weights[i,h] + delta_v[i,h]
                
            for h in range(1,H):
                for j in range(D):
                    w_weights[h,j] = w_weights[h,j] + delta_w[h,j]
        
        
        
        
        score = get_accuracy(x, r,H,K,D, v_weights, w_weights)
        
        #Adaptive learning
        error_new = score
        
        if (error_new >= error_prev):
            delta_step_size = a
        else:
            delta_step_size =  -1.0*step_size*b

        #print("epoc:" + str(run) + " prev_accuracy:" + str(np.round(error_prev*100,5)) + " accuracy:" + str(np.round(error_new*100,5)))
        
        error_prev =  error_new 
        step_size = step_size + delta_step_size  

        #print("delta_step_size:" + str(np.round(delta_step_size,5))  + " new_step_size:" + str(np.round(step_size,5)))
       
        if (score >= accuracy_stop):
            print("Converged - Overall Training Accuracy: " + str(score*100))
            print("Total Iterations:" + str(run))
            return (v_weights,w_weights)

        
    # max iteration reached
    print("No Convergence - Training Accuracy: " + str(score*100))
    return (v_weights,w_weights)

In [9]:
#convergence is based on overall training accuracy hitting 'wanted' accuracy (in this case 50%)
result = back_prop(X,R,H,K,D,0.5,0.5,5,0,0,0)
result


Converged - Overall Training Accuracy: 53.333333333333336
Total Iterations:4


(array([[-1.65558541,  0.25229155,  0.25962139,  0.27091144,  0.25274038,
          0.26517332,  0.22496464,  0.27417369,  0.26601028,  0.26025148],
        [ 1.16276529, -0.80919903, -0.82635145, -0.85584825, -0.8388272 ,
         -0.85341166, -0.8019358 , -0.84733481, -0.84007985, -0.83859564],
        [ 0.48295967,  0.56810984,  0.57386168,  0.57848401,  0.5719651 ,
          0.58072984,  0.55821115,  0.58126446,  0.57657906,  0.5692592 ]]),
 array([[ 0.        ,  0.        ,  0.        ,  0.        ],
        [-0.11833467, -0.16301565, -0.9099968 , -0.30001257],
        [-0.10386869, -0.14571492, -0.91874338, -0.31486824],
        [-0.08511665, -0.14996919, -0.93026645, -0.31716495],
        [-0.11074312, -0.14401126, -0.91765646, -0.31246459],
        [-0.09300248, -0.14463732, -0.92364179, -0.31735767],
        [-0.1307411 , -0.15446456, -0.90009033, -0.29745952],
        [-0.09091929, -0.14133055, -0.9296786 , -0.32188152],
        [-0.10382942, -0.15048351, -0.91898193, -0.3133

In [10]:
print (get_accuracy(X, R,H,K,D, result[0],result[1])) 


0.5333333333333333


In [11]:
result = back_prop(X,R,H,K,D,0.05,0.9,2000,0,0,0)
print (get_accuracy(X, R,H,K,D, result[0],result[1]))

Converged - Overall Training Accuracy: 90.0
Total Iterations:841
0.9


In [12]:
result = back_prop(X,R,H,K,D,0.05,0.9,2000,0.3,0,0)
print (get_accuracy(X, R,H,K,D, result[0],result[1]))

Converged - Overall Training Accuracy: 90.0
Total Iterations:667
0.9


In [17]:
result = back_prop(X,R,H,K,D,0.05,0.9,2000,0,0.01,0.9)
print (get_accuracy(X, R,H,K,D, result[0],result[1]))

Converged - Overall Training Accuracy: 90.0
Total Iterations:426
0.9


In [14]:
result = back_prop(X,R,H,K,D,0.05,0.9,2000,0.3,0.01,0.9)
print (get_accuracy(X, R,H,K,D, result[0],result[1]))

Converged - Overall Training Accuracy: 90.0
Total Iterations:250
0.9
